apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mern-traffic-policy
  namespace: mern-app
spec:
  podSelector: {}  # S'applique à tous les pods du namespace
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: 3002  # frontend → backend

    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 27017  # backend → MongoDB

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 3002  # frontend → backend

    - to:
        - podSelector:
            matchLabels:
              app: mongodb
      ports:
        - protocol: TCP
          port: 27017  # backend → MongoDB
